title: Rock Robotics
email: rock-dev@dfki.de
baseurl: rock-core.github.io
defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
source: src

